apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: resume-issuer
  namespace: default
spec:
  acme:
    email: liujin834@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: resume-issuer-key
    solvers:
      - http01:
          ingress:
            class: traefik
